apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretgen-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://carvel-dev.github.io/helm-charts/
    chart: secretgen-controller
    targetRevision: "0.12.0"
    helm:
      values: |
        secretgenController:
          namespace: secretgen-controller
          createNamespace: true
  destination:
    server: https://kubernetes.default.svc
    namespace: secretgen-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true